import dynamic from 'next/dynamic';

import { Inter } from "next/font/google";
import { Cormorant_Garamond } from "next/font/google";



import "./globals.css";

const inter = Inter({ subsets: ["latin"] , weight: ["100", "200", "300", "400", "700"] });
const cormorant = Cormorant_Garamond({ subsets: ["latin"], weight: ["300", "400", "500", "600", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
